name: Commit Workflow

on:
  push:
  workflow_dispatch:

jobs:

  commands-ok:
    name: Ensure main commands do not fail
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Commands
        run: |
          set -x
          date
          pwd
          whoami
          make deps build
          ls -lah bin/launchr
          mkdir -p .compose/build/
          touch .compose/build/test
          ./bin/launchr release
          export file="$(ls -t .compose/artifacts/ | head -n 1)"; echo ${file}
          tar -tf .compose/artifacts/${file}

  go-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commands
        run: |
          set -x
          date
          pwd
          whoami
          make lint

  go-tests:
    name: Run Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commands
        run: |
          set -x
          date
          pwd
          whoami
          make test

